engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  fixme:
    enabled: true
    exclude_paths:
      - *.md
      - *.yml
ratings:
  paths:
    - app/**
    - lib/**

exclude_paths:
  - config/**/*
  - spec/**/*
  - db/**/*
  - rubocop.yml