language: ruby

rvm:
 - "2.2.3"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp .env.sample .env
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
  
script:
  - bundle exec rspec